---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php5
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name : install apache2 and php package for CentOS
    yum:
      name:
        - apache2
        - libapache2-mod-php5
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
