---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: install updates ( Ubuntu )
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks: 
    
  - name: create dizi user
    tags: always
    user:
      name: dizi
      groups: root

  - name: add ssh key for dizi
    tags: always
    authorized_key:
      user: dizi
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDA8rKgtuAZ8TysCbxQ28scmHa5oN1Nk5llu+sxEYG/6 ansible"

  - name: add sudoers file for dizi
    tags: always
    copy:
      src: sudoer_dizi
      dest: /etc/sudoers.d/dizi
      owner: root
      group: root

- hosts: workstations
  become: true
  tasks: 

  - name: install unzip
    package: 
      name: unzip

- hosts: web_servers
  become: true
  tasks: 

  - name: install apache2 and php package for Ubuntu
    tags: apache,apache2,httpd
    apt:
      name:
        - apache2
        - libapache2-mod-php5
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name : install apache2 and php package for CentOS
    tags: apache,apache2,httpd
    dnf:
      name:
        - apache2
        - libapache2-mod-php5
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: start httpd ( CentOS )
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change timeout in apache2.conf 
    tags: apache,ubuntu,httpd
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^Timeout'
      line: Timeout 299
    when: ansible_distribution == "Ubuntu" 
    register: apache2

  - name: restart apache ( Ubuntu )
    tags: apache2,ubuntu,httpd
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package ( CentOS )
    tags: centos,db,mariadb
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package ( Ubuntu )
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

