- name: add ssh key for dizi
  authorized_key:
    user: dizi
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDA8rKgtuAZ8TysCbxQ28scmHa5oN1Nk5llu+sxEYG/6 ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
